# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20, verbose_name='名字')),
                ('gpic', models.ImageField(upload_to='upload', verbose_name='图片')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价钱')),
                ('isDelete', models.BooleanField(default=False)),
                ('gunit', models.CharField(default='500g', max_length=20, verbose_name='单位')),
                ('gclick', models.IntegerField(default=0, verbose_name='点击')),
                ('gjianjie', models.CharField(max_length=200)),
                ('gkucun', models.IntegerField(default=100, verbose_name='库存')),
                ('gcontent', tinymce.models.HTMLField(default='很好', verbose_name='描述')),
            ],
            options={
                'verbose_name': '水果',
                'verbose_name_plural': '水果',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价钱')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('isTrue', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.GoodsInfo')),
            ],
            options={
                'verbose_name_plural': '发货管理',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(auto_now=True, verbose_name='购买日期')),
                ('oIsPay', models.BooleanField(default=False, verbose_name='是否付款')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='总价')),
                ('oaddress', models.CharField(max_length=150, verbose_name='收货地址')),
            ],
            options={
                'verbose_name_plural': '订单管理',
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='销量')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='销售额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.GoodsInfo')),
            ],
            options={
                'verbose_name_plural': '销量查看',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20, verbose_name='种类')),
                ('type_img', models.CharField(default='', max_length=500)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '水果类型修改',
            },
        ),
        migrations.CreateModel(
            name='User_ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(default='', max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_ticket',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=500, verbose_name='密码')),
                ('uemail', models.CharField(max_length=30, verbose_name='电子邮箱')),
                ('ushow', models.CharField(default='', max_length=20, verbose_name='收件人名字')),
                ('uaddress', models.CharField(default='', max_length=100, verbose_name='收件地址')),
                ('uyoubian', models.CharField(default='', max_length=6, verbose_name='收件邮编')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='收件人电话')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.AddField(
            model_name='user_ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UserInfo'),
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.OrderInfo'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.TypeInfo'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.GoodsInfo'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UserInfo'),
        ),
    ]
